---

- name: setup elasticsearch
  block:
    - name: set elasticsearch.yml (custom)
      copy:
        src: "{{ custom_elasticsearch_conf }}"
        backup: yes
        dest: /etc/elasticsearch/elasticsearch.yml
        group: root
        owner: root
        mode: 0644
      when: custom_elasticsearch_conf is defined
  become: yes
  tags:
    - setup
