

- name: install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: install java-1.8.0-openjdk.x86_64
  yum:
    name: java-1.8.0-openjdk.x86_64
    state: present
    update_cache: yes

- name: get elasticsearch-{{ elasticsearch_version }}.rpm
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}.rpm"
    dest: "/tmp/elasticsearch-{{ elasticsearch_version }}.rpm"

- name: install elasticsearch {{ elasticsearch_version }}
  yum:
    name: "/tmp/elasticsearch-{{ elasticsearch_version }}.rpm"
  register: install_elasticsearch

- name: create /etc/ansible_installed_elasticsearch{{ elasticsearch_version }}
  file:
    path: "/etc/ansible_installed_elasticsearch{{ elasticsearch_version }}"
    state: touch
  when: install_elasticsearch.changed

- name: Ensure Elasticsearch enabled
  service:
    name: elasticsearch
    state: started
    enabled: yes
  when: ansible_distribution_major_version == 6

- name: Ensure Elasticsearch enabled
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
  when: ansible_distribution_major_version == 7

- name: install plugin
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ item }}"
  args:
    creates: /etc/ansible_installed_elasticsearch_plugins
  with_items:
    - "{{ install_plugins }}"
  when: install_plugins is defined
  register: install_elasticsearch_plugins

- name: create /etc/ansible_installed_elasticsearch_plugins
  file:
    path: "/etc/ansible_installed_elasticsearch_plugins"
    state: touch
  when: install_elasticsearch_plugins.changed
