
- apt: name="software-properties-common" state=present update_cache=yes

- apt_repository:
    repo: 'ppa:webupd8team/java'

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: yes

- name: Install oracle-java8-installer
  apt: name="{{ item }}" state=present update_cache=yes force=yes
  with_items:
    - oracle-java8-installer

- name: get elasticsearch-{{ elasticsearch_version }}.deb (https://artifacts.elastic.co)
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb"
    dest: "/tmp/elasticsearch-{{ elasticsearch_version }}.deb"
  ignore_errors: yes
  register: get_elasticsearch

- name: get elasticsearch-{{ elasticsearch_version }}.deb (https://download.elastic.co)
  get_url:
    url: "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb"
    dest: "/tmp/elasticsearch-{{ elasticsearch_version }}.deb"
  when: get_elasticsearch.failed

- name: install elasticsearch {{ elasticsearch_version }}
  apt: deb=/tmp/elasticsearch-{{ elasticsearch_version }}.deb
  register: install_elasticsearch

- name: create /etc/ansible_installed_elasticsearch{{ elasticsearch_version }}
  file:
    path: "/etc/ansible_installed_elasticsearch{{ elasticsearch_version }}"
    state: touch
  when: install_elasticsearch.changed

- name: Ensure Elasticsearch enabled
  service:
    name: elasticsearch
    state: started
    enabled: yes
  when: ansible_distribution_version == "14.04"

- name: Ensure Elasticsearch enabled
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
  when: ansible_distribution_version == "16.04"

- name: install plugin
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ item }}"
  args:
    creates: /etc/ansible_installed_elasticsearch_plugins
  with_items:
    - "{{ install_plugins }}"
  when: install_plugins is defined
  register: install_elasticsearch_plugins

- name: create /etc/ansible_installed_elasticsearch_plugins
  file:
    path: "/etc/ansible_installed_elasticsearch_plugins"
    state: touch
  when: install_elasticsearch_plugins.changed
