

- apt_repository:
    repo: 'ppa:webupd8team/java'

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: yes

- name: Install oracle-java8-installer
  apt: name="{{ item }}" state=present update_cache=yes force=yes
  with_items:
    - oracle-java8-installer

- name: get elasticsearch-{{ elasticsearch_version }}.deb
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb"
    dest: "/tmp/elasticsearch-{{ elasticsearch_version }}.deb"

- name: install elasticsearch {{ elasticsearch_version }}
  apt: deb=/tmp/elasticsearch-{{ elasticsearch_version }}.deb
  register: install_elasticsearch

- name: create /etc/ansible_installed_elasticsearch{{ elasticsearch_version }}
  file:
    path: "/etc/ansible_installed_elasticsearch{{ elasticsearch_version }}"
    state: touch
  when: install_elasticsearch.changed

- name: install plugin
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ item }}"
  with_items:
    - "{{ install_plugins }}"
  when: install_plugins is defined
